spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/ms_tickets
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
server:
  port: 8082
